databases:
  - name: somali-subtitles-db
    plan: free
    databaseName: somali_subtitles

services:
  - type: web
    name: somaliscribe
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URI
        fromDatabase:
          name: somali-subtitles-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
